### ISSUE TITLE
getconnection methods gives closed connections

### ISSUE THREAD

**Issue by jibin-tj** [blue-color/nodejdbc#6]
Hi 

I am closing a connection after statement execution like
`                   db.getConnection()
    			.then(conn => {
    				console.log("closing conn")
    				conn.close();
    			}`
 and when i try to get a new connection like
` db.getConnection()
    	 	.then(conn => {
    	 		console.timeEnd("getconinprocessdate")
    	 		return conn.createStatement()})
    	 	.then(st => {
    	 		console.log("c");
    	 		return st.executeQuery(constants.queries.GET_PROCESS_DATE);
    	 	})`

I am getting connection already closed error.

Is this a bug ? or should I again initilise db like
`db= new NodeJDBC(dbOptions);`
everytime i need  connection ?

**Comment by ceyhunkerti** [comment]
with the new update
db.getConnection(true) 
returns a new connection if the connection is closed

**Comment by jibin-tj** [comment]
Hi
I think this code will break when we first call getConnection(true) the connection because ` if (!this._connection) ` is left blank.

**Comment by ceyhunkerti** [comment]
sorry i forgot that while restructuring the block.
fixed and pushed.

thanks.

**Comment by jibin-tj** [comment]
Hi

I guess you forgot something else also. The code is breaking with trace 
`C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\nodejdbc\lib\nodejdbc.js:31
      conn = java.callStaticMethodAsync('java.sql.DriverManager', 'getConnection', this.config.url, this.config.username, this.config.password);
                                                                                              ^

TypeError: Cannot read property 'url' of undefined
    at module.exports.newConnection (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\nodejdbc\lib\nodejdbc.js:31:95)
    at NodeJDBC.module.exports.NodeJDBC.getConnection (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\nodejdbc\lib\nodejdbc.js:42:35)`

**Comment by jibin-tj** [comment]
Hi
 Reference to 'this'  is null because of the change `  NodeJDBC.prototype.newConnection` to `newConnection` . Please fix the bug.

**Comment by ceyhunkerti** [comment]
ok this time it should work. 

i was using node 6x and there is an issue with the node-java package so i was unable to test nodejdbc.
Switched to node 4x and tested the fixes now.

thanks again.

**Comment by jibin-tj** [comment]
Hi @ceyhunkerti 

There is again some other issue. I am getting the trace `Unhandled rejection TypeError: this._connection.isClosed is not a function
    at NodeJDBC.module.exports.NodeJDBC.getConnection (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\nodejdbc\lib\nodejdbc.js:41:35)
    at C:\Users\a5tv\NodeWorkspace\PurchaseOrder\routes\project.js:670:23
    at PassThroughHandlerContext.finallyHandler (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\finally.js:55:23)
    at PassThroughHandlerContext.tryCatcher (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._settlePromise (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:574:21)
    at Promise._settlePromise0 (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._resolveCallback (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise._settlePromiseFromHandler (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:561:18)`

**Comment by ceyhunkerti** [comment]
hi,can you pull and try again.

**Comment by jibin-tj** [comment]
Hi

Again there is some issue.
There 1 extra _ in `me.__connection`

**Comment by ceyhunkerti** [comment]
ok fixed that.

**Comment by jibin-tj** [comment]
Thank you @ceyhunkerti

**Comment by jibin-tj** [comment]
Hi 
Again I am getting an error. Trace is `Unhandled rejection TypeError: circular promise resolution chain

    See http://goo.gl/MqrFmX

    at makeSelfResolutionError (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:4:12)
    at Promise._resolveCallback (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:423:37)
    at Promise._settlePromiseFromHandler (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromiseCtx (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\promise.js:598:10)
    at Async._drainQueue (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\async.js:143:12)
    at Async._drainQueues (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\a5tv\NodeWorkspace\PurchaseOrder\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`

**Comment by ceyhunkerti** [comment]
added another fix

**Comment by jibin-tj** [comment]
Hi
I am still getting `java.sql.BatchUpdateException: [Teradata JDBC Driver] [TeraJDBC 15.10.00.14] [Error 1095] [SQLState HY000] Cannot call a method on closed connection`
when using 
getConnection(true) ,getConnection() and closing , and again using getConnection(true) returns closed connection.

**Comment by ceyhunkerti** [comment]
Hi, I could not reproduce the error

	NodeJDBC = require '../lib/nodejdbc'
	config =
	    libs : ['sqlite-jdbc-3.8.11.2.jar']
	    className: 'org.sqlite.JDBC'
	    url: 'jdbc:sqlite:test.db'
	
	db = new NodeJDBC config
	
	db.getConnection(true).then ->
	  db.getConnection().then (con)->
	    con.close().then (c)->
	      console.log con.isClosed()
	      db.getConnection(true).then (con)->
	        console.log con.isClosed()

**Comment by jibin-tj** [comment]
sorry i messed up. Working fine now. Thank you @ceyhunkerti
